### ISSUE TITLE
Specifying a datacenter does not limit the datastore search

### ISSUE THREAD

**Issue by geokala** [cloudify-cosmo/cloudify-vsphere-plugin#61]
When a VM is deployed, the biggest datastore is selected, ignoring whether it's actually in the datacenter that the VM will be deployed to.

Understandably, this can cause errors.

**Comment by scrossan** [comment]
I realise that this is an old issue, but we're actually running into this problem at my workplace with the 2.2.1 version of the plugin.

[I've created a gist with the debug output, showing logging related to the host selection](https://gist.github.com/scrossan/4d85692fe267c14c8031c624f7351d3f). In this case I'm trying to deploy a host using the Cloudify vSphere Plugin v2.2.1 from Cloudify Manager v3.2.1, to a data center called "Dev". In my blueprint I'm passing in lists of `allowed_hosts` and `allowed_datastores` which contain the dev hosts and datastore, but apparently these are being ignored because as you see in the gist our production hosts and datastores are being considered as deployment hosts for the VM as well.

Since PROD_VSAN has the most free space, prod2.example.com (I'm not sure why a prod hosts is being selected instead of a dev host) and PROD_VSAN are being selected as the deployment hosts.

This is the result of the deployment:
```
[vm_ix7o5p.start] Task failed 'vsphere_server_plugin.server.start' -> Error during executing task on vSphere: '(vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: spec.location.folder',
   faultCause = (vim.fault.DatacenterMismatch) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = 'The input arguments had entities that did not belong to the same datacenter.',
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      invalidArgument = (vim.fault.DatacenterMismatch.Argument) [
         (vim.fault.DatacenterMismatch.Argument) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            entity = 'vim.Folder:group-vx',
            inputDatacenter = 'vim.Datacenter:datacenter-y'
         }
      ],
      expectedDatacenter = 'vim.Datacenter:datacenter-z'
   },
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = u'spec.location.folder'
}'
```

**Comment by 0lvin** [comment]
What Cloudify Manager do you use? 

Recommended version for use 2.2.1 plugin version is 3.3+, look to https://github.com/cloudify-cosmo/cloudify-vsphere-plugin/blob/2.2.1/setup.py#L32

**Comment by scrossan** [comment]
Sorry, I made a small typo - the version of Cloudify Manager we're using in this environment is actually v3.4.0. I'll update my comment.

**Comment by geokala** [comment]
You should be seeing the output: "Filtered list of hosts to be considered: {hosts}" if the allowed_hosts is being passed through correctly. Are you able to gist that part of your blueprint (with anything anonymised that needs to be)?

**Comment by geokala** [comment]
Also (though it won't affect this issue), I recommend you update to at least 2.3.0 of the plugin, if not the most recent release. There were a lot of bug fixes in 2.3.0 that might help you avoid running into problems once this one is resolved.

**Comment by scrossan** [comment]
@geokala I've [updated my gist](https://gist.github.com/scrossan/4d85692fe267c14c8031c624f7351d3f) with the full debug output from the job, and it seems that `allowed_hosts` isn't being passed through correctly. I'm working on getting the blueprints to you.

**Comment by 0lvin** [comment]
Issue is not reproducible after 2.3.0 release, close issue for now.
